import { Ingredient, INGREDIENT_KEYS, INGREDIENT_KINDS } from "./ingredient.types"

export const INGREDIENTS: Ingredient[] = [
  // ---------- Ingredientes-base ----------
  {
    id: 'base-1',
    key: INGREDIENT_KEYS.WATER,
    image: '/images/ingredients/water.png',
    kind: INGREDIENT_KINDS.WATER,
    popularName: 'Água',
    properties: ['solvente', 'base aquosa'],
    observation: 'Usada como veículo em chás, lambedores e cataplasmas.',
  },
  {
    id: 'base-2',
    key: INGREDIENT_KEYS.OIL,
    image: '/images/ingredients/oil.png',
    kind: INGREDIENT_KINDS.OIL,
    popularName: 'Óleo',
    properties: ['veículo lipídico', 'potencializador de princípios ativos'],
    observation: 'Usado para potencializar princípios ativos de cataplasmas e pós.',
  },
  {
    id: 'base-3',
    key: INGREDIENT_KEYS.ALCOHOL,
    image: '/images/ingredients/alcohol.png',
    kind: INGREDIENT_KINDS.ALCOHOL,
    popularName: 'Álcool',
    properties: ['conservante', 'extrator alcoólico'],
    observation: 'Usado como base de maceração em garrafadas (pode ser aguardente).',
  },

  // ---------- Plantas ----------
  {
    id: '1',
    key: INGREDIENT_KEYS.ANGICO,
    image: '/images/ingredients/angico.png',
    kind: INGREDIENT_KINDS.PLANT,
    popularName: 'Angico',
    scientificName: 'Anadenanthera colubrina (Vell.) Brenan',
    family: 'Fabaceae',
    properties: ['expectorante', 'anti-inflamatória', 'cicatrizante'],
    observation:
      'Arbusto a árvore grande, decídua. Folhas compostas bipinadas, flores em capítulos brancos, fruto tipo vagem.',
  },
  {
    id: '2',
    key: INGREDIENT_KEYS.GUINE,
    image: '/images/ingredients/guine.png',
    kind: INGREDIENT_KINDS.PLANT,
    popularName: 'Guiné (Mucura-caá)',
    scientificName: 'Petiveria alliacea L.',
    family: 'Phytolaccaceae',
    properties: ['anti-inflamatória', 'analgésica', 'antimicrobiana', 'sedativa'],
    observation:
      'Subarbusto ereto perene, folhas simples alternas, flores brancas ou amareladas em espigas. Nativa da Amazônia, usada em rituais indígenas.',
  },
  {
    id: '3',
    key: INGREDIENT_KEYS.JURUBEBA,
    image: '/images/ingredients/jurubeba.png',
    kind: INGREDIENT_KINDS.PLANT,
    popularName: 'Jurubeba',
    scientificName: 'Solanum paniculatum',
    family: 'Solanaceae',
    properties: ['cicatrizante', 'diurético', 'digestivo'],
    observation:
      'Arbusto de caule espinhoso, perene. Flores em panículas lilás, fruto tipo baga amarelada. Contém alcaloides e saponinas.',
  },
  {
    id: '4',
    key: INGREDIENT_KEYS.JATOBA,
    image: '/images/ingredients/jatoba.png',
    kind: INGREDIENT_KINDS.PLANT,
    popularName: 'Jatobá',
    scientificName: 'Hymenaea courbaril',
    family: 'Fabaceae',
    properties: ['anti-inflamatória', 'expectorante'],
    observation:
      'Árvore grande e resinosa, semidecídua. Flores avermelhadas em panículas, fruto tipo vagem lenhosa castanho-escura.',
  },
  {
    id: '5',
    key: INGREDIENT_KEYS.HORTELA,
    image: '/images/ingredients/hortela.png',
    kind: INGREDIENT_KINDS.PLANT,
    popularName: 'Hortelã',
    scientificName: 'Mentha sp.',
    family: 'Lamiaceae',
    properties: ['calmante'],
    observation: 'Erva aromática rasteira e perene, folhas simples lanceoladas.',
  },
  {
    id: '6',
    key: INGREDIENT_KEYS.ROMA,
    image: '/images/ingredients/roma.png',
    kind: INGREDIENT_KINDS.PLANT,
    popularName: 'Romã',
    scientificName: 'Punica granatum L.',
    family: 'Lythraceae',
    properties: ['anti-inflamatória', 'antioxidante'],
    observation: 'Arbusto alto ou árvore pequena, perene. Flor vermelho-alaranjada, fruto globoide com numerosas sementes.',
  },
  {
    id: '7',
    key: INGREDIENT_KEYS.ASSA_PEIXE,
    image: '/images/ingredients/assa-peixe.png',
    kind: INGREDIENT_KINDS.PLANT,
    popularName: 'Assa-peixe',
    scientificName: 'Vernonanthura brasiliana (L.) H.Rob',
    family: 'Asteraceae',
    properties: ['antioxidante', 'expectorante', 'anti-inflamatória'],
    observation: 'Arbusto perene, folhas simples, inflorescência apical.',
  },
  {
    id: '8',
    key: INGREDIENT_KEYS.MASTRUCO,
    image: '/images/ingredients/mastruco.png',
    kind: INGREDIENT_KINDS.PLANT,
    popularName: 'Erva-de-santa-maria (Mastruço)',
    scientificName: 'Dysphania ambrosioides (L.) Mosyakin & Clemants',
    family: 'Amaranthaceae',
    properties: [
      'antiparasitária (vermífuga)',
      'antimicrobiana',
      'antifúngica',
      'anti-inflamatória',
      'expectorante',
      'digestiva',
    ],
    observation: 'Erva anual, folhas simples irregularmente denteadas. Também conhecida como mastruz.',
  },
  {
    id: '9',
    key: INGREDIENT_KEYS.CAJUEIRO,
    image: '/images/ingredients/cajueiro.png',
    kind: INGREDIENT_KINDS.PLANT,
    popularName: 'Cajueiro',
    scientificName: 'Anacardium occidentale L.',
    family: 'Anacardiaceae',
    properties: ['antimicrobiana', 'anti-inflamatória', 'cicatrizante'],
    observation:
      'Árvore ou arbusto perene, folhas ovaladas coriáceas. Fruto tipo noz reniforme com pseudofruto carnoso.',
  },
  {
    id: '10',
    key: INGREDIENT_KEYS.AROEIRA,
    image: '/images/ingredients/aroeira.png',
    kind: INGREDIENT_KINDS.PLANT,
    popularName: 'Aroeira-mansa',
    scientificName: 'Schinus terebinthifolius',
    family: 'Anacardiaceae',
    properties: ['anti-inflamatória', 'adstringente', 'cicatrizante'],
    observation: 'Árvore grande, folhas alternadas, flores pequenas roxas em racemos.',
  },
  {
    id: '11',
    key: INGREDIENT_KEYS.BARBATIMAO,
    image: '/images/ingredients/barbatimao.png',
    kind: INGREDIENT_KINDS.PLANT,
    popularName: 'Barbatimão',
    scientificName: 'Abarema cochliacarpos',
    family: 'Fabaceae',
    properties: ['antimicrobiana', 'gastroprotetora', 'cicatrizante'],
    observation:
      'Árvore de porte elevado, típica do Cerrado. Casca espessa escura, rica em taninos e fenólicos.',
  },
  {
    id: '12',
    key: INGREDIENT_KEYS.CASCA_DE_ANTA,
    image: '/images/ingredients/casca-de-anta.png',
    kind: INGREDIENT_KINDS.PLANT,
    popularName: 'Casca-de-anta',
    scientificName: 'Drimys brasiliensis Miers',
    family: 'Winteraceae',
    properties: ['anti-inflamatória', 'antinociceptiva', 'antiulcerativa'],
    observation: 'Árvore ou arbusto, folhas elípticas, flores solitárias, fruto avermelhado ou enegrecido.',
  },
  {
    id: '13',
    key: INGREDIENT_KEYS.ACAFRAO_DA_TERRA,
    image: '/images/ingredients/acafrao-da-terra.png',
    kind: INGREDIENT_KINDS.PLANT,
    popularName: 'Açafrão-da-terra (Açafroa)',
    scientificName: 'Curcuma longa L.',
    family: 'Zingiberaceae',
    properties: ['anti-inflamatória', 'antioxidante', 'hepatoprotetora'],
    observation:
      'Planta herbácea rizomatosa perene. Rizoma amarelo-alaranjado, rico em curcuminoides.',
  },
  {
    id: '14',
    key: INGREDIENT_KEYS.QUINA_DO_CERRADO,
    image: '/images/ingredients/quina-do-cerrado.png',
    kind: INGREDIENT_KINDS.PLANT,
    popularName: 'Quina-do-cerrado',
    scientificName: 'Strychnos pseudoquina',
    family: 'Loganiaceae',
    properties: ['antitumoral', 'anti-inflamatória', 'antioxidante', 'antiviral'],
    observation:
      'Planta arbórea de pequeno a médio porte, perene, típica do Cerrado (Goiás e Minas Gerais).',
  },
  {
    id: '15',
    key: INGREDIENT_KEYS.GENGIBRE,
    image: '/images/ingredients/gengibre.png',
    kind: INGREDIENT_KINDS.PLANT,
    popularName: 'Gengibre',
    scientificName: 'Zingiber officinale',
    family: 'Zingiberaceae',
    properties: ['digestivo', 'anti-inflamatório'],
    observation:
      'Erva rizomatosa robusta. Usado junto com o açafrão-da-terra na receita de cataplasma anti-inflamatório.',
  },
]
