import { Ingredient } from "./ingredient.types";

export const INGREDIENTS: Ingredient[] = [
  {
    id: "1",
    popularName: "Alecrim",
    scientificName: "Rosmarinus officinalis",
    family: "Lamiaceae",
    properties: ["antioxidante", "digestivo", "estimulante"],
    observation: "Muito usado na culinária e em infusões.",
    references: "https://pt.wikipedia.org/wiki/Alecrim",
    concepts: ["erva aromática", "medicinal"],
    drawing_priority: "high",
  },
  {
    id: "2",
    popularName: "Hortelã",
    scientificName: "Mentha spicata",
    family: "Lamiaceae",
    properties: ["refrescante", "digestivo"],
    observation: "Comum em chás e sucos.",
    references: "https://pt.wikipedia.org/wiki/Hortel%C3%A3",
    concepts: ["erva medicinal"],
    drawing_priority: "medium",
  },
  {
    id: "3",
    popularName: "Camomila",
    scientificName: "Matricaria chamomilla",
    family: "Asteraceae",
    properties: ["calmante", "anti-inflamatório"],
    observation: "Indicada para ansiedade e sono.",
    references: "https://pt.wikipedia.org/wiki/Camomila",
    concepts: ["flor medicinal"],
    drawing_priority: "low",
  },
  {
    id: "4",
    popularName: "Babosa",
    scientificName: "Aloe vera",
    family: "Asphodelaceae",
    properties: ["cicatrizante", "hidratante"],
    observation: "Usada em tratamentos de pele.",
    references: "https://pt.wikipedia.org/wiki/Aloe_vera",
    concepts: ["planta suculenta"],
    drawing_priority: "high",
  },
  {
    id: "5",
    popularName: "Erva-doce",
    scientificName: "Foeniculum vulgare",
    family: "Apiaceae",
    properties: ["digestivo", "calmante"],
    observation: "Muito usada em chás.",
    references: "https://pt.wikipedia.org/wiki/Erva-doce",
    concepts: ["semente aromática"],
    drawing_priority: "medium",
  },
]