import { Ingredient, INGREDIENT_KEYS } from "./ingredient.types";

export const INGREDIENTS: Ingredient[] = [
  {
    id: '1',
    key: INGREDIENT_KEYS.ROSEMARY,
    popularName: 'Alecrim',
    scientificName: 'Rosmarinus officinalis',
    family: 'Lamiaceae',
    properties: ['antioxidante', 'digestivo', 'estimulante'],
    observation: 'Muito usado na culinária e em infusões.',
    references: 'https://pt.wikipedia.org/wiki/Alecrim',
    concepts: ['erva aromática', 'medicinal'],
  },
  {
    id: '2',
    key: 'MINT',
    popularName: 'Hortelã',
    scientificName: 'Mentha spicata',
    family: 'Lamiaceae',
    properties: ['refrescante', 'digestivo'],
    observation: 'Comum em chás e sucos.',
    references: 'https://pt.wikipedia.org/wiki/Hortel%C3%A3',
    concepts: ['erva medicinal'],
  },
  {
    id: '3',
    key: 'CHAMOMILE',
    popularName: 'Camomila',
    scientificName: 'Matricaria chamomilla',
    family: 'Asteraceae',
    properties: ['calmante', 'anti-inflamatório'],
    observation: 'Indicada para ansiedade e sono.',
    references: 'https://pt.wikipedia.org/wiki/Camomila',
    concepts: ['flor medicinal'],
  },
  {
    id: '4',
    key: 'ALOE',
    popularName: 'Babosa',
    scientificName: 'Aloe vera',
    family: 'Asphodelaceae',
    properties: ['cicatrizante', 'hidratante'],
    observation: 'Usada em tratamentos de pele.',
    references: 'https://pt.wikipedia.org/wiki/Aloe_vera',
    concepts: ['planta suculenta'],
  },
  {
    id: '5',
    key: 'FENNEL',
    popularName: 'Erva-doce',
    scientificName: 'Foeniculum vulgare',
    family: 'Apiaceae',
    properties: ['digestivo', 'calmante'],
    observation: 'Muito usada em chás.',
    references: 'https://pt.wikipedia.org/wiki/Erva-doce',
    concepts: ['semente aromática'],
  },
]